"use client";

import { AlertTriangle, ChevronLeft, ChevronRight, PiggyBank, Save } from "lucide-react";
import Link from "next/link";
import { useActionState } from "react";
import { saveBudget } from "@/app/orcamento/actions";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { formatCurrency } from "@/lib/formatters";

type Row = { id: string; nome: string; cor: string; icone: string; planned: number; actual: number };
export function BudgetManager({ month, rows }: { month: string; rows: Row[] }) { const totalPlanned = rows.reduce((sum, item) => sum + item.planned, 0); const totalActual = rows.reduce((sum, item) => sum + item.actual, 0); const balance = totalPlanned - totalActual; return <div className="space-y-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-primary">Orçamento base zero</p><h1 className="mt-1 font-display text-3xl font-bold tracking-[-.04em] sm:text-4xl">Dê uma missão à sua grana</h1><p className="mt-2 text-sm text-muted-foreground">Planeje por categoria e acompanhe o realizado do mês.</p></div><MonthPicker month={month} /></header>
  <section className="grid gap-3 sm:grid-cols-3"><Metric label="Planejado" value={totalPlanned} /><Metric label="Realizado" value={totalActual} /><Metric label={balance >= 0 ? "Ainda disponível" : "Acima do plano"} value={Math.abs(balance)} negative={balance < 0} /></section>
  {rows.length ? <section className="space-y-3">{rows.map((row) => <BudgetRow key={row.id} month={month} row={row} />)}</section> : <Card><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><PiggyBank className="mb-4 size-8 text-primary" /><h2 className="font-display text-xl font-bold">Sem categorias de despesa</h2><p className="mt-2 text-sm text-muted-foreground">Crie categorias para começar seu planejamento.</p></CardContent></Card>}
  </div>; }
function BudgetRow({ month, row }: { month: string; row: Row }) { const [state, action, pending] = useActionState(saveBudget, {}); const percentage = row.planned > 0 ? row.actual / row.planned * 100 : row.actual > 0 ? 100 : 0; const exceeded = row.actual > row.planned && row.actual > 0; return <Card className="rounded-2xl"><CardContent className="p-5"><div className="flex flex-col gap-5 md:flex-row md:items-center"><span className="size-3 shrink-0 rounded-full" style={{ backgroundColor: row.cor }} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-4"><p className="font-bold">{row.nome}</p><p className={`text-sm font-bold ${exceeded ? "text-negative" : ""}`}>{formatCurrency(row.actual)} <span className="font-normal text-muted-foreground">de {formatCurrency(row.planned)}</span></p></div><Progress className="mt-3" value={Math.min(100, percentage)} /><p className="mt-2 text-xs text-muted-foreground">{row.planned === 0 ? "Defina o limite desta categoria" : exceeded ? `${formatCurrency(row.actual - row.planned)} acima do planejado` : `${formatCurrency(row.planned - row.actual)} disponíveis`}</p></div><form action={action} className="flex items-center gap-2"><input type="hidden" name="categoryId" value={row.id} /><input type="hidden" name="month" value={month} /><Input className="w-32" name="amount" inputMode="decimal" defaultValue={moneyInput(row.planned)} aria-label={`Planejado para ${row.nome}`} /><Button size="icon" disabled={pending} aria-label={`Salvar ${row.nome}`}><Save /></Button></form></div>{exceeded ? <p className="mt-3 flex items-center gap-2 text-xs font-bold text-negative"><AlertTriangle className="size-4" /> Categoria acima do orçamento.</p> : null}{state.message ? <Alert className={`mt-3 ${state.status === "error" ? "border-negative/40" : "border-positive/40"}`}><AlertDescription>{state.message}</AlertDescription></Alert> : null}</CardContent></Card>; }
function MonthPicker({ month }: { month: string }) { const date = new Date(`${month}T00:00:00Z`); const prev = new Date(date); prev.setUTCMonth(prev.getUTCMonth() - 1); const next = new Date(date); next.setUTCMonth(next.getUTCMonth() + 1); const href = (value: Date) => `/orcamento?mes=${value.toISOString().slice(0, 7)}`; return <div className="flex items-center gap-2 rounded-2xl border border-border bg-surface p-1"><Button asChild variant="ghost" size="icon"><Link href={href(prev)} aria-label="Mês anterior"><ChevronLeft /></Link></Button><p className="min-w-32 text-center text-sm font-bold capitalize">{new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" }).format(date)}</p><Button asChild variant="ghost" size="icon"><Link href={href(next)} aria-label="Próximo mês"><ChevronRight /></Link></Button></div>; }
function Metric({ label, value, negative }: { label: string; value: number; negative?: boolean }) { return <Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-2 font-display text-2xl font-bold ${negative ? "text-negative" : ""}`}>{formatCurrency(value)}</p></CardContent></Card>; }
function moneyInput(value: number) { return new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }
