"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { parseBrazilianMoney } from "@/lib/formatters";
import { createClient } from "@/lib/supabase/server";

export type GoalState = { status?: "success" | "error"; message?: string };
const optionalAccount = z.union([z.literal("none"), z.string().uuid()]).transform((value) => value === "none" ? null : value);
const goalSchema = z.object({ id: z.string().uuid().optional(), nome: z.string().trim().min(2, "Informe o nome da meta.").max(100), descricao: z.string().trim().max(500).optional(), valorAlvo: z.string().transform(parseBrazilianMoney).pipe(z.number().finite().positive("Informe um valor-alvo maior que zero.")), valorInicial: z.string().transform(parseBrazilianMoney).pipe(z.number().finite().min(0)), dataInicio: z.coerce.date(), dataAlvo: z.coerce.date(), cor: z.string().regex(/^#[0-9a-f]{6}$/i) }).refine((v) => v.dataAlvo >= v.dataInicio, { path: ["dataAlvo"], message: "A data-alvo deve ser posterior ao início." });
const movementSchema = z.object({ goalId: z.string().uuid(), accountId: optionalAccount, tipo: z.enum(["aporte", "resgate", "ajuste"]), valor: z.string().transform(parseBrazilianMoney).pipe(z.number().finite().positive("Informe um valor maior que zero.")), data: z.coerce.date(), observacao: z.string().trim().max(500).optional() }).superRefine((v, ctx) => { if (v.tipo === "ajuste" && v.accountId) ctx.addIssue({ code: "custom", path: ["accountId"], message: "Ajustes não movimentam uma conta." }); });
async function auth() { const supabase = await createClient(); const { data } = await supabase.auth.getClaims(); return { supabase, userId: data?.claims?.sub }; }
function refresh() { revalidatePath("/metas"); revalidatePath("/dashboard"); revalidatePath("/contas"); }

export async function saveGoal(_: GoalState, form: FormData): Promise<GoalState> { const parsed = goalSchema.safeParse(Object.fromEntries(form)); if (!parsed.success) return { status: "error", message: parsed.error.issues[0]?.message ?? "Revise os dados." }; const { supabase, userId } = await auth(); if (!userId) return { status: "error", message: "Sua sessão expirou." }; const v = parsed.data; const values = { nome: v.nome, descricao: v.descricao || null, valor_alvo: v.valorAlvo, valor_inicial: v.valorInicial, data_inicio: v.dataInicio.toISOString().slice(0,10), data_alvo: v.dataAlvo.toISOString().slice(0,10), cor: v.cor }; const result = v.id ? await supabase.from("goals").update(values).eq("id", v.id).eq("user_id", userId).select("id").single() : await supabase.from("goals").insert({ ...values, valor_atual: v.valorInicial, user_id: userId }).select("id").single(); if (result.error) return { status: "error", message: "Não foi possível salvar a meta." }; refresh(); return { status: "success", message: v.id ? "Meta atualizada." : "Meta criada." }; }
export async function addGoalMovement(_: GoalState, form: FormData): Promise<GoalState> { const parsed = movementSchema.safeParse(Object.fromEntries(form)); if (!parsed.success) return { status: "error", message: parsed.error.issues[0]?.message ?? "Revise os dados." }; const { supabase, userId } = await auth(); if (!userId) return { status: "error", message: "Sua sessão expirou." }; const v = parsed.data; const { error } = await supabase.from("goal_contributions").insert({ user_id: userId, goal_id: v.goalId, account_id: v.tipo === "ajuste" ? null : v.accountId, tipo: v.tipo, valor: v.valor, data: v.data.toISOString().slice(0,10), observacao: v.observacao || null }); if (error) return { status: "error", message: "Não foi possível registrar a movimentação." }; refresh(); return { status: "success", message: v.tipo === "aporte" ? "Aporte registrado." : v.tipo === "resgate" ? "Resgate registrado." : "Saldo da meta ajustado." }; }
export async function changeGoalStatus(_: GoalState, form: FormData): Promise<GoalState> { const parsed = z.object({ id: z.string().uuid(), status: z.enum(["ativa", "pausada", "cancelada"]) }).safeParse(Object.fromEntries(form)); if (!parsed.success) return { status: "error", message: "Meta inválida." }; const { supabase, userId } = await auth(); if (!userId) return { status: "error", message: "Sua sessão expirou." }; const { error } = await supabase.from("goals").update({ status: parsed.data.status }).eq("id", parsed.data.id).eq("user_id", userId).select("id").single(); if (error) return { status: "error", message: "Não foi possível alterar a meta." }; refresh(); return { status: "success", message: "Status da meta atualizado." }; }
export async function deleteGoalMovement(_: GoalState, form: FormData): Promise<GoalState> { const id = z.string().uuid().safeParse(form.get("id")); if (!id.success) return { status: "error", message: "Movimentação inválida." }; const { supabase, userId } = await auth(); if (!userId) return { status: "error", message: "Sua sessão expirou." }; const { error } = await supabase.from("goal_contributions").delete().eq("id", id.data).eq("user_id", userId); if (error) return { status: "error", message: "Não foi possível excluir a movimentação." }; refresh(); return { status: "success", message: "Movimentação removida e saldo recalculado." }; }
