"use client";

import { Archive, CalendarDays, CreditCard, Pencil, Plus, ReceiptText, RotateCcw, ShoppingBag, XCircle } from "lucide-react";
import { useActionState, useId } from "react";
import { archiveCard, cancelPurchase, createPurchase, restoreCard, saveCard } from "@/app/cartoes/actions";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { formatCurrency } from "@/lib/formatters";

type Account = { id: string; nome: string; instituicao: string };
type Category = { id: string; nome: string; cor: string };
type CreditCardData = { id: string; account_id: string | null; ativo: boolean; bandeira: string; cor: string; dia_fechamento: number; dia_vencimento: number; instituicao: string; limite_total: number; nome: string; ultimos_quatro_digitos: string | null; used: number };
type Invoice = { id: string; card_id: string; data_fechamento: string; data_vencimento: string; status: string; valor_total: number; cardName: string; cardColor: string };
type Purchase = { id: string; descricao: string; valor_total: number; numero_parcelas: number; data_compra: string; cancelada_em: string | null; cardName: string; cardColor: string; categoryName: string; installments: { numero_parcela: number; valor: number; data_vencimento: string; status: string }[] };
const brands = ["Visa", "Mastercard", "Elo", "American Express", "Hipercard", "Outra"];
const colors = ["#7C3AED", "#145C43", "#2563EB", "#D97706", "#DC2626", "#18181B"];

export function CardManager({ cards, accounts, categories, invoices, purchases }: { cards: CreditCardData[]; accounts: Account[]; categories: Category[]; invoices: Invoice[]; purchases: Purchase[] }) {
  const active = cards.filter((card) => card.ativo); const archived = cards.filter((card) => !card.ativo);
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-primary">Cartões e parcelas</p><h1 className="mt-1 font-display text-3xl font-bold tracking-[-.04em] sm:text-4xl">Faturas sem surpresa</h1><p className="mt-2 text-sm text-muted-foreground">Limites, fechamentos e compras parceladas no lugar certo.</p></div><div className="flex flex-wrap gap-2"><PurchaseDialog cards={active} categories={categories} trigger={<Button variant="outline" disabled={!active.length}><ShoppingBag /> Nova compra</Button>} /><CardDialog accounts={accounts} trigger={<Button><Plus /> Novo cartão</Button>} /></div></div>
    <Tabs defaultValue="cartoes"><TabsList className="w-full justify-start overflow-x-auto sm:w-auto"><TabsTrigger value="cartoes">Cartões</TabsTrigger><TabsTrigger value="faturas">Faturas</TabsTrigger><TabsTrigger value="compras">Compras</TabsTrigger></TabsList>
      <TabsContent value="cartoes"><CardsPanel active={active} archived={archived} accounts={accounts} /></TabsContent>
      <TabsContent value="faturas"><InvoicesPanel invoices={invoices} /></TabsContent>
      <TabsContent value="compras"><PurchasesPanel purchases={purchases} /></TabsContent>
    </Tabs>
  </div>;
}

function CardsPanel({ active, archived, accounts }: { active: CreditCardData[]; archived: CreditCardData[]; accounts: Account[] }) { return <div className="space-y-8">{active.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.map((card) => <CreditCardItem key={card.id} card={card} accounts={accounts} />)}</div> : <Empty icon={CreditCard} title="Nenhum cartão ativo" text="Cadastre um cartão para organizar faturas e parcelamentos." />}{archived.length ? <section><h2 className="mb-3 text-sm font-bold text-muted-foreground">Cartões arquivados</h2><div className="space-y-2">{archived.map((card) => <div key={card.id} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 opacity-75"><span className="size-3 rounded-full" style={{ backgroundColor: card.cor }} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{card.nome}</p><p className="text-xs text-muted-foreground">{card.instituicao}</p></div><RestoreCardButton id={card.id} /></div>)}</div></section> : null}</div>; }
function CreditCardItem({ card, accounts }: { card: CreditCardData; accounts: Account[] }) { const available = Math.max(0, card.limite_total - card.used); const usage = card.limite_total ? Math.min(100, card.used / card.limite_total * 100) : 0; return <div className="relative min-h-64 overflow-hidden rounded-3xl p-6 text-white shadow-premium" style={{ backgroundColor: card.cor }}><div className="absolute -end-16 -top-16 size-44 rounded-full bg-white/10" /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-white/70">{card.instituicao}</p><h2 className="mt-1 font-display text-xl font-bold">{card.nome}</h2></div><div className="flex"><CardDialog card={card} accounts={accounts} trigger={<Button className="text-white hover:bg-white/15" variant="ghost" size="icon" aria-label={`Editar ${card.nome}`}><Pencil /></Button>} /><ArchiveCardDialog card={card} /></div></div><div className="mt-auto"><p className="text-sm tracking-[.24em] text-white/80">•••• {card.ultimos_quatro_digitos ?? "••••"}</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{ width: `${usage}%` }} /></div><div className="mt-3 flex items-end justify-between"><div><p className="text-xs text-white/70">Disponível</p><p className="mt-0.5 font-display text-lg font-bold">{formatCurrency(available)}</p></div><div className="text-right"><p className="text-xs text-white/70">Fecha dia {card.dia_fechamento}</p><p className="text-xs font-bold">Vence dia {card.dia_vencimento}</p></div></div></div></div></div>; }

function InvoicesPanel({ invoices }: { invoices: Invoice[] }) { return invoices.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{invoices.map((invoice) => <Card key={invoice.id} className="rounded-2xl"><CardContent className="p-5"><div className="flex items-start justify-between"><span className="rounded-xl bg-subtle p-3"><ReceiptText className="size-5 text-primary" /></span><Badge className={invoice.status === "atrasada" ? "bg-negative/10 text-negative" : "bg-brand-soft text-primary"}>{invoice.status}</Badge></div><p className="mt-5 text-sm font-bold">{invoice.cardName}</p><p className="mt-1 font-display text-2xl font-bold">{formatCurrency(invoice.valor_total)}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border pt-4 text-xs"><div><p className="text-muted-foreground">Fechamento</p><p className="mt-1 font-bold">{dateBR(invoice.data_fechamento)}</p></div><div><p className="text-muted-foreground">Vencimento</p><p className="mt-1 font-bold">{dateBR(invoice.data_vencimento)}</p></div></div></CardContent></Card>)}</div> : <Empty icon={CalendarDays} title="Nenhuma fatura gerada" text="As faturas aparecerão automaticamente quando você cadastrar compras." />; }
function PurchasesPanel({ purchases }: { purchases: Purchase[] }) { return purchases.length ? <div className="space-y-3">{purchases.map((purchase) => <Card key={purchase.id} className="rounded-2xl"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="rounded-xl bg-subtle p-3"><ShoppingBag className="size-5 text-primary" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{purchase.descricao}</p>{purchase.cancelada_em ? <Badge className="bg-negative/10 text-negative">cancelada</Badge> : null}</div><p className="mt-1 text-xs text-muted-foreground">{purchase.cardName} · {purchase.categoryName} · {dateBR(purchase.data_compra)}</p><p className="mt-1 text-xs text-muted-foreground">{purchase.numero_parcelas === 1 ? "À vista" : `${purchase.numero_parcelas}x · próxima ${nextInstallment(purchase.installments)}`}</p></div><p className="font-display text-lg font-bold">{formatCurrency(purchase.valor_total)}</p>{!purchase.cancelada_em ? <CancelPurchaseDialog purchase={purchase} /> : null}</CardContent></Card>)}</div> : <Empty icon={ShoppingBag} title="Nenhuma compra cadastrada" text="Cadastre compras para gerar parcelas e faturas automaticamente." />; }

function CardDialog({ card, accounts, trigger }: { card?: CreditCardData; accounts: Account[]; trigger: React.ReactNode }) { const [state, action, pending] = useActionState(saveCard, {}); const selectId = useId(); return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{card ? "Editar cartão" : "Novo cartão"}</DialogTitle><DialogDescription>Informe limite e datas para organizarmos as faturas corretamente.</DialogDescription></DialogHeader><form action={action} className="space-y-5">{card ? <input type="hidden" name="id" value={card.id} /> : null}<div className="grid gap-5 sm:grid-cols-2"><Field name="nome" label="Nome do cartão" placeholder="Cartão principal" defaultValue={card?.nome} /><Field name="instituicao" label="Banco emissor" placeholder="Ex.: Nubank" defaultValue={card?.instituicao} /><SelectField id={`${selectId}-brand`} name="bandeira" label="Bandeira" defaultValue={card?.bandeira ?? "Mastercard"} options={brands.map((value) => ({ value, label: value }))} /><Field name="ultimosQuatro" label="Últimos 4 dígitos" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="1234" defaultValue={card?.ultimos_quatro_digitos ?? ""} required={false} /><Field name="limite" label="Limite total (R$)" inputMode="decimal" defaultValue={card ? inputMoney(card.limite_total) : "0,00"} /><SelectField id={`${selectId}-account`} name="accountId" label="Conta para pagamento" defaultValue={card?.account_id ?? "none"} options={[{ value: "none", label: "Sem conta vinculada" }, ...accounts.map((account) => ({ value: account.id, label: `${account.nome} · ${account.instituicao}` }))]} /><Field name="diaFechamento" label="Dia de fechamento" type="number" min={1} max={31} defaultValue={card?.dia_fechamento} /><Field name="diaVencimento" label="Dia de vencimento" type="number" min={1} max={31} defaultValue={card?.dia_vencimento} /></div><ColorPicker defaultValue={card?.cor ?? colors[0]} />{state.message ? <Feedback state={state} /> : null}<div className="flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Cancelar</Button></DialogClose><Button disabled={pending}>{pending ? "Salvando…" : "Salvar cartão"}</Button></div></form></DialogContent></Dialog>; }
function PurchaseDialog({ cards, categories, trigger }: { cards: CreditCardData[]; categories: Category[]; trigger: React.ReactNode }) { const [state, action, pending] = useActionState(createPurchase, {}); const id = useId(); return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Nova compra</DialogTitle><DialogDescription>As parcelas serão distribuídas nas faturas conforme o fechamento do cartão.</DialogDescription></DialogHeader><form action={action} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><SelectField id={`${id}-card`} name="cardId" label="Cartão" defaultValue={cards[0]?.id} options={cards.map((card) => ({ value: card.id, label: card.nome }))} /><SelectField id={`${id}-category`} name="categoryId" label="Categoria" defaultValue={categories[0]?.id} options={categories.map((category) => ({ value: category.id, label: category.nome }))} /><Field name="descricao" label="Descrição" placeholder="Ex.: Geladeira" /><Field name="valorTotal" label="Valor total (R$)" inputMode="decimal" placeholder="0,00" /><Field name="numeroParcelas" label="Número de parcelas" type="number" min={1} max={360} defaultValue={1} /><Field name="dataCompra" label="Data da compra" type="date" defaultValue={todayBR()} /><div className="sm:col-span-2"><Field name="dataPrimeiraParcela" label="Primeiro vencimento (opcional)" type="date" required={false} /></div></div><div className="space-y-2"><Label htmlFor={`${id}-note`}>Observação (opcional)</Label><Textarea id={`${id}-note`} name="observacao" maxLength={500} /></div>{state.message ? <Feedback state={state} /> : null}<div className="flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Cancelar</Button></DialogClose><Button disabled={pending || !categories.length}>{pending ? "Gerando parcelas…" : "Registrar compra"}</Button></div></form></DialogContent></Dialog>; }
function ArchiveCardDialog({ card }: { card: CreditCardData }) { const [state, action, pending] = useActionState(archiveCard, {}); return <Dialog><DialogTrigger asChild><Button className="text-white hover:bg-white/15" variant="ghost" size="icon" aria-label={`Arquivar ${card.nome}`}><Archive /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Arquivar {card.nome}?</DialogTitle><DialogDescription>O cartão deixa de aceitar novas compras, mas as faturas e parcelas permanecem preservadas.</DialogDescription></DialogHeader><form action={action}><input type="hidden" name="id" value={card.id} />{state.message ? <Feedback state={state} /> : null}<div className="mt-5 flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Cancelar</Button></DialogClose><Button variant="destructive" disabled={pending}>{pending ? "Arquivando…" : "Arquivar cartão"}</Button></div></form></DialogContent></Dialog>; }
function CancelPurchaseDialog({ purchase }: { purchase: Purchase }) { const [state, action, pending] = useActionState(cancelPurchase, {}); return <Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Cancelar ${purchase.descricao}`}><XCircle /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Cancelar esta compra?</DialogTitle><DialogDescription>Todas as parcelas pendentes serão canceladas e os totais das faturas serão recalculados. Essa ação mantém o registro para auditoria.</DialogDescription></DialogHeader><form action={action}><input type="hidden" name="id" value={purchase.id} />{state.message ? <Feedback state={state} /> : null}<div className="mt-5 flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Voltar</Button></DialogClose><Button variant="destructive" disabled={pending}>{pending ? "Cancelando…" : "Cancelar compra"}</Button></div></form></DialogContent></Dialog>; }
function RestoreCardButton({ id }: { id: string }) { const [, action, pending] = useActionState(restoreCard, {}); return <form action={action}><input type="hidden" name="id" value={id} /><Button variant="outline" size="sm" disabled={pending}><RotateCcw />{pending ? "Restaurando…" : "Restaurar"}</Button></form>; }

function Field({ name, label, ...props }: React.ComponentProps<typeof Input> & { name: string; label: string }) { const id = useId(); return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} required {...props} /></div>; }
function SelectField({ id, name, label, defaultValue, options }: { id: string; name: string; label: string; defaultValue?: string; options: { value: string; label: string }[] }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Select name={name} defaultValue={defaultValue}><SelectTrigger id={id}><SelectValue /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>; }
function ColorPicker({ defaultValue }: { defaultValue: string }) { return <div><Label>Cor do cartão</Label><div className="mt-2 flex flex-wrap gap-3">{colors.map((color) => <label key={color} className="cursor-pointer"><input className="peer sr-only" type="radio" name="cor" value={color} defaultChecked={color.toLowerCase() === defaultValue.toLowerCase()} /><span className="block size-8 rounded-full border-4 border-background ring-2 ring-transparent peer-checked:ring-foreground" style={{ backgroundColor: color }} /></label>)}</div></div>; }
function Feedback({ state }: { state: { status?: "success" | "error"; message?: string } }) { return <Alert className={state.status === "error" ? "border-negative/40" : "border-positive/40"}><AlertDescription>{state.message}</AlertDescription></Alert>; }
function Empty({ icon: Icon, title, text }: { icon: typeof CreditCard; title: string; text: string }) { return <Card><CardContent className="flex min-h-64 flex-col items-center justify-center p-6 text-center"><span className="mb-4 rounded-2xl bg-brand-soft p-4 text-primary"><Icon /></span><h2 className="font-display text-xl font-bold">{title}</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">{text}</p></CardContent></Card>; }
function inputMoney(value: number) { return new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }
function dateBR(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function todayBR() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function nextInstallment(items: Purchase["installments"]) { const item = items.filter((entry) => entry.status === "pendente" || entry.status === "atrasada").sort((a, b) => a.data_vencimento.localeCompare(b.data_vencimento))[0]; return item ? `${item.numero_parcela}ª de ${formatCurrency(item.valor)} em ${dateBR(item.data_vencimento)}` : "sem parcelas pendentes"; }
