"use client";

import { Archive, Landmark, Pencil, Plus, RotateCcw } from "lucide-react";
import { useActionState, useId } from "react";
import { archiveAccount, restoreAccount, saveAccount } from "@/app/contas/actions";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { formatCurrency } from "@/lib/formatters";
import type { Database } from "@/types/database";

type AccountRow = Database["public"]["Tables"]["accounts"]["Row"];
type Account = Pick<AccountRow, "id" | "nome" | "instituicao" | "tipo" | "saldo_atual" | "cor" | "inclui_no_patrimonio" | "ativa">;
const typeLabels: Record<Account["tipo"], string> = { corrente: "Conta corrente", poupanca: "Poupança", investimento: "Investimentos", dinheiro: "Dinheiro", carteira_digital: "Carteira digital" };
const colors = ["#145C43", "#7C3AED", "#2563EB", "#D97706", "#DC2626", "#475569"];

export function AccountManager({ accounts }: { accounts: Account[] }) {
  const active = accounts.filter((account) => account.ativa);
  const archived = accounts.filter((account) => !account.ativa);
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-primary">Contas bancárias</p><h1 className="mt-1 font-display text-3xl font-bold tracking-[-.04em] sm:text-4xl">Onde sua grana vive</h1><p className="mt-2 text-sm text-muted-foreground">Saldos manuais, organizados em um só lugar.</p></div><AccountDialog trigger={<Button><Plus /> Nova conta</Button>} /></div>
    {active.length ? <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.map((account) => <AccountCard key={account.id} account={account} />)}</section> : <Card><CardContent className="flex min-h-72 flex-col items-center justify-center text-center"><span className="mb-5 rounded-2xl bg-brand-soft p-4 text-primary"><Landmark /></span><h2 className="font-display text-xl font-bold">Sua primeira conta começa aqui</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">Cadastre banco, tipo e saldo atual para compor seu patrimônio.</p><AccountDialog trigger={<Button className="mt-6"><Plus /> Criar conta</Button>} /></CardContent></Card>}
    {archived.length ? <section><h2 className="mb-3 text-sm font-bold text-muted-foreground">Contas arquivadas</h2><div className="space-y-2">{archived.map((account) => <div key={account.id} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 opacity-75"><span className="size-3 rounded-full" style={{ backgroundColor: account.cor }} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{account.nome}</p><p className="text-xs text-muted-foreground">{account.instituicao}</p></div><RestoreButton id={account.id} /></div>)}</div></section> : null}
  </div>;
}

function AccountCard({ account }: { account: Account }) { return <Card className="group relative overflow-hidden rounded-2xl"><div className="absolute inset-x-0 top-0 h-1" style={{ backgroundColor: account.cor }} /><CardContent className="p-5 sm:p-6"><div className="flex items-start justify-between"><span className="rounded-xl bg-subtle p-3 text-primary"><Landmark className="size-5" /></span><div className="flex gap-1"><AccountDialog account={account} trigger={<Button variant="ghost" size="icon" aria-label={`Editar ${account.nome}`}><Pencil /></Button>} /><ArchiveDialog account={account} /></div></div><div className="mt-6"><div className="flex items-center gap-2"><h2 className="truncate font-display text-lg font-bold">{account.nome}</h2>{!account.inclui_no_patrimonio ? <Badge>fora do patrimônio</Badge> : null}</div><p className="mt-1 text-xs text-muted-foreground">{account.instituicao} · {typeLabels[account.tipo]}</p><p className="mt-5 font-display text-2xl font-bold tracking-[-.04em]">{formatCurrency(Number(account.saldo_atual))}</p><p className="mt-1 text-xs text-muted-foreground">Saldo informado</p></div></CardContent></Card>; }

function AccountDialog({ account, trigger }: { account?: Account; trigger: React.ReactNode }) { const [state, action, pending] = useActionState(saveAccount, {}); return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{account ? "Editar conta" : "Nova conta"}</DialogTitle><DialogDescription>{account ? "Atualize os dados e o saldo informado." : "Adicione uma conta para acompanhar seu patrimônio."}</DialogDescription></DialogHeader><form action={action} className="space-y-5">{account ? <input type="hidden" name="id" value={account.id} /> : null}<div className="grid gap-5 sm:grid-cols-2"><Field name="nome" label="Nome da conta" placeholder="Conta principal" defaultValue={account?.nome} /><Field name="instituicao" label="Banco ou instituição" placeholder="Ex.: Banco do Brasil" defaultValue={account?.instituicao} /><div className="space-y-2"><Label htmlFor={`tipo-${account?.id ?? "new"}`}>Tipo</Label><Select name="tipo" defaultValue={account?.tipo ?? "corrente"}><SelectTrigger id={`tipo-${account?.id ?? "new"}`}><SelectValue /></SelectTrigger><SelectContent>{Object.entries(typeLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><Field name="saldo" label="Saldo atual (R$)" inputMode="decimal" defaultValue={account ? formatInputMoney(Number(account.saldo_atual)) : "0,00"} /></div><div><Label>Cor da conta</Label><div className="mt-2 flex flex-wrap gap-3">{colors.map((color) => <label key={color} className="cursor-pointer"><input className="peer sr-only" type="radio" name="cor" value={color} defaultChecked={color.toLowerCase() === (account?.cor ?? colors[0]).toLowerCase()} /><span className="block size-8 rounded-full border-4 border-background ring-2 ring-transparent peer-checked:ring-foreground" style={{ backgroundColor: color }} /></label>)}</div></div><label className="flex cursor-pointer items-start gap-3 rounded-xl bg-subtle p-4"><Checkbox name="incluiNoPatrimonio" defaultChecked={account?.inclui_no_patrimonio ?? true} /><span><span className="block text-sm font-bold">Incluir no patrimônio</span><span className="mt-0.5 block text-xs text-muted-foreground">O saldo entra no total consolidado do dashboard.</span></span></label>{state.message ? <Alert className={state.status === "error" ? "border-negative/40" : "border-positive/40"}><AlertDescription>{state.message}</AlertDescription></Alert> : null}<div className="flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Cancelar</Button></DialogClose><Button disabled={pending}>{pending ? "Salvando…" : "Salvar conta"}</Button></div></form></DialogContent></Dialog>; }

function ArchiveDialog({ account }: { account: Account }) { const [state, action, pending] = useActionState(archiveAccount, {}); return <Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Arquivar ${account.nome}`}><Archive /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Arquivar {account.nome}?</DialogTitle><DialogDescription>A conta sairá do dashboard, mas transações e histórico serão preservados. Você poderá restaurá-la depois.</DialogDescription></DialogHeader><form action={action}><input type="hidden" name="id" value={account.id} />{state.message ? <Alert className="mb-4"><AlertDescription>{state.message}</AlertDescription></Alert> : null}<div className="flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Cancelar</Button></DialogClose><Button variant="destructive" disabled={pending}>{pending ? "Arquivando…" : "Arquivar conta"}</Button></div></form></DialogContent></Dialog>; }
function RestoreButton({ id }: { id: string }) { const [, action, pending] = useActionState(restoreAccount, {}); return <form action={action}><input type="hidden" name="id" value={id} /><Button variant="outline" size="sm" disabled={pending}><RotateCcw /> {pending ? "Restaurando…" : "Restaurar"}</Button></form>; }
function Field({ name, label, ...props }: React.ComponentProps<typeof Input> & { name: string; label: string }) { const id = useId(); return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} required {...props} /></div>; }
function formatInputMoney(value: number) { return new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }
