"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { parseBrazilianMoney } from "@/lib/formatters";
import { createClient } from "@/lib/supabase/server";
export type DebtState={status?:"success"|"error";message?:string};
const money=z.string().transform(parseBrazilianMoney).pipe(z.number().finite().min(0)); const optionalMoney=z.string().transform(v=>v.trim()?parseBrazilianMoney(v):null).pipe(z.number().min(0).nullable()); const optionalDate=z.string().transform(v=>v||null); const optionalInt=z.string().transform(v=>v?Number(v):null).pipe(z.number().int().positive().nullable());
const debtSchema=z.object({id:z.string().uuid().optional(),nome:z.string().trim().min(2).max(120),credor:z.string().trim().min(2).max(120),tipo:z.enum(["cartao","emprestimo","consignado","financiamento","boleto","negativada","outra"]),valorOriginal:money.pipe(z.number().positive()),saldoDevedor:money,taxaJuros:optionalMoney,dataContratacao:optionalDate,dataVencimento:optionalDate,negativada:z.string().optional().transform(Boolean),emAtraso:z.string().optional().transform(Boolean),numeroParcelas:optionalInt,parcelasPagas:z.coerce.number().int().min(0),valorParcela:optionalMoney,ofertaQuitacao:optionalMoney,validadeOferta:optionalDate,status:z.enum(["aberta","negociada","quitada","contestada","cancelada"]),prioridade:z.enum(["baixa","media","alta","urgente"]),observacao:z.string().trim().max(1000).optional()}).refine(v=>v.saldoDevedor<=v.valorOriginal,{message:"O saldo não pode superar o valor original."}).refine(v=>v.ofertaQuitacao===null||v.ofertaQuitacao<=v.saldoDevedor,{message:"A oferta não pode superar o saldo devedor."});
const paymentSchema=z.object({debtId:z.string().uuid(),accountId:z.union([z.literal("none"),z.string().uuid()]).transform(v=>v==="none"?null:v),valor:money.pipe(z.number().positive()),dataPagamento:z.coerce.date(),tipo:z.enum(["parcela","extra","quitacao","desconto","ajuste"]),observacao:z.string().trim().max(500).optional()}).superRefine((v,c)=>{if(["desconto","ajuste"].includes(v.tipo)&&v.accountId)c.addIssue({code:"custom",message:"Descontos e ajustes não movimentam conta.",path:["accountId"]})});
async function auth(){const supabase=await createClient();const{data}=await supabase.auth.getClaims();return{supabase,userId:data?.claims?.sub}}function refresh(){revalidatePath("/dividas");revalidatePath("/dashboard");revalidatePath("/contas")}
export async function saveDebt(_:DebtState,form:FormData):Promise<DebtState>{const p=debtSchema.safeParse(Object.fromEntries(form));if(!p.success)return{status:"error",message:p.error.issues[0]?.message??"Revise os dados."};const{supabase,userId}=await auth();if(!userId)return{status:"error",message:"Sua sessão expirou."};const v=p.data;const values={nome:v.nome,credor:v.credor,tipo:v.tipo,valor_original:v.valorOriginal,saldo_devedor:v.saldoDevedor,taxa_juros_mensal:v.taxaJuros,data_contratacao:v.dataContratacao,data_vencimento:v.dataVencimento,negativada:v.negativada,em_atraso:v.emAtraso,numero_parcelas:v.numeroParcelas,parcelas_pagas:v.parcelasPagas,valor_parcela:v.valorParcela,oferta_quitacao:v.ofertaQuitacao,validade_oferta:v.validadeOferta,status:v.saldoDevedor===0?"quitada" as const:v.status,prioridade:v.prioridade,observacao:v.observacao||null};const r=v.id?await supabase.from("debts").update(values).eq("id",v.id).eq("user_id",userId).select("id").single():await supabase.from("debts").insert({...values,user_id:userId}).select("id").single();if(r.error)return{status:"error",message:"Não foi possível salvar a dívida."};refresh();return{status:"success",message:v.id?"Dívida atualizada.":"Dívida cadastrada."}}
export async function addDebtPayment(_:DebtState,form:FormData):Promise<DebtState>{const p=paymentSchema.safeParse(Object.fromEntries(form));if(!p.success)return{status:"error",message:p.error.issues[0]?.message??"Revise os dados."};const{supabase,userId}=await auth();if(!userId)return{status:"error",message:"Sua sessão expirou."};const v=p.data;const{error}=await supabase.from("debt_payments").insert({user_id:userId,debt_id:v.debtId,account_id:["desconto","ajuste"].includes(v.tipo)?null:v.accountId,valor:v.valor,data_pagamento:v.dataPagamento.toISOString().slice(0,10),tipo:v.tipo,observacao:v.observacao||null});if(error)return{status:"error",message:error.message.includes("exceeds")?"O valor supera o saldo da dívida.":"Não foi possível registrar o pagamento."};refresh();return{status:"success",message:"Pagamento registrado e saldos atualizados."}}
export async function deleteDebtPayment(_:DebtState,form:FormData):Promise<DebtState>{const id=z.string().uuid().safeParse(form.get("id"));if(!id.success)return{status:"error",message:"Pagamento inválido."};const{supabase,userId}=await auth();if(!userId)return{status:"error",message:"Sua sessão expirou."};const{error}=await supabase.from("debt_payments").delete().eq("id",id.data).eq("user_id",userId);if(error)return{status:"error",message:"Não foi possível remover o pagamento."};refresh();return{status:"success",message:"Pagamento removido e saldos restaurados."}}
