create index account_balance_history_account_owner_idx on public.account_balance_history (account_id, user_id);
create index account_balance_history_owner_idx on public.account_balance_history (user_id);
create index budgets_category_owner_idx on public.budgets (category_id, user_id);
create index card_invoices_card_owner_idx on public.card_invoices (card_id, user_id);
create index cards_account_owner_idx on public.cards (account_id, user_id) where account_id is not null;
create index categories_parent_owner_idx on public.categories (categoria_pai_id, user_id) where categoria_pai_id is not null;
create index goal_contributions_account_owner_idx on public.goal_contributions (account_id, user_id) where account_id is not null;
create index goal_contributions_goal_owner_idx on public.goal_contributions (goal_id, user_id);
create index goal_contributions_owner_idx on public.goal_contributions (user_id);
create index installments_invoice_owner_idx on public.installments (card_invoice_id, user_id);
create index installments_purchase_owner_idx on public.installments (purchase_id, user_id);
create index purchases_card_owner_idx on public.purchases (card_id, user_id);
create index purchases_category_owner_idx on public.purchases (category_id, user_id);
create index recurrence_rules_account_owner_idx on public.recurrence_rules (account_id, user_id);
create index recurrence_rules_category_owner_idx on public.recurrence_rules (category_id, user_id);
create index transactions_account_owner_idx on public.transactions (account_id, user_id);
create index transactions_category_owner_idx on public.transactions (category_id, user_id) where category_id is not null;
create index transactions_installment_owner_idx on public.transactions (installment_id, user_id) where installment_id is not null;
create index transactions_recurrence_owner_idx on public.transactions (recurrence_rule_id, user_id) where recurrence_rule_id is not null;
create index transactions_transfer_owner_idx on public.transactions (transfer_account_id, user_id) where transfer_account_id is not null;
