"use client";

import { CalendarDays, CheckCircle2, Pause, Pencil, Plus, RotateCcw, Target, Trash2, TrendingUp, Wallet } from "lucide-react";
import { useActionState, useId, useState } from "react";
import { addGoalMovement, changeGoalStatus, deleteGoalMovement, saveGoal, type GoalState } from "@/app/metas/actions";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { formatCurrency } from "@/lib/formatters";

type Account = { id: string; nome: string; instituicao: string; cor: string };
type Contribution = { id: string; goal_id: string; account_id: string | null; valor: number; tipo: "aporte" | "resgate" | "ajuste"; data: string; observacao: string | null; accountName: string | null };
type Goal = { id: string; nome: string; descricao: string | null; valor_alvo: number; valor_inicial: number; valor_atual: number; data_inicio: string; data_alvo: string; cor: string; status: "ativa" | "concluida" | "pausada" | "cancelada"; contributions: Contribution[] };
const colors = ["#145C43", "#7C3AED", "#2563EB", "#D97706", "#DC2626", "#A75478"];

export function GoalManager({ goals, accounts }: { goals: Goal[]; accounts: Account[] }) { const active = goals.filter((g) => g.status === "ativa" || g.status === "pausada"); const completed = goals.filter((g) => g.status === "concluida"); const saved = goals.reduce((sum,g) => sum + g.valor_atual, 0); return <div className="space-y-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-primary">Metas financeiras</p><h1 className="mt-1 font-display text-3xl font-bold tracking-[-.04em] sm:text-4xl">Planos que viram patrimônio</h1><p className="mt-2 text-sm text-muted-foreground">Acompanhe o ritmo, faça aportes e saiba quando cada objetivo ficará pronto.</p></div><GoalDialog trigger={<Button><Plus /> Nova meta</Button>} /></header><section className="grid gap-3 sm:grid-cols-3"><Metric icon={Target} label="Metas em andamento" value={String(active.length)} /><Metric icon={Wallet} label="Total reservado" value={formatCurrency(saved)} /><Metric icon={CheckCircle2} label="Metas concluídas" value={String(completed.length)} /></section><Tabs defaultValue="ativas"><TabsList><TabsTrigger value="ativas">Em andamento</TabsTrigger><TabsTrigger value="concluidas">Concluídas</TabsTrigger></TabsList><TabsContent value="ativas"><GoalGrid goals={active} accounts={accounts} /></TabsContent><TabsContent value="concluidas"><GoalGrid goals={completed} accounts={accounts} /></TabsContent></Tabs></div>; }
function GoalGrid({ goals, accounts }: { goals: Goal[]; accounts: Account[] }) { return goals.length ? <div className="grid gap-5 lg:grid-cols-2">{goals.map((goal) => <GoalCard key={goal.id} goal={goal} accounts={accounts} />)}</div> : <Card><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><Target className="mb-4 size-8 text-primary" /><h2 className="font-display text-xl font-bold">Nenhuma meta por aqui</h2><p className="mt-2 text-sm text-muted-foreground">Crie um objetivo e transforme intenção em progresso mensurável.</p></CardContent></Card>; }
function GoalCard({ goal, accounts }: { goal: Goal; accounts: Account[] }) { const progress = Math.min(100, goal.valor_atual / goal.valor_alvo * 100); const projection = calculateProjection(goal); return <Card className="overflow-hidden rounded-3xl"><div className="h-1.5" style={{ backgroundColor: goal.cor }} /><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-xl font-bold">{goal.nome}</h2><Badge>{status(goal.status)}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Meta para {dateBR(goal.data_alvo)}</p></div><div className="flex"><GoalDialog goal={goal} trigger={<Button variant="ghost" size="icon" aria-label={`Editar ${goal.nome}`}><Pencil /></Button>} /><StatusButtons goal={goal} /></div></div><p className="mt-6 font-display text-3xl font-bold">{formatCurrency(goal.valor_atual)}</p><p className="mt-1 text-sm text-muted-foreground">de {formatCurrency(goal.valor_alvo)}</p><Progress className="mt-4" value={progress} /><div className="mt-2 flex justify-between text-xs"><span className="font-bold">{progress.toFixed(0)}%</span><span className="text-muted-foreground">Faltam {formatCurrency(Math.max(0, goal.valor_alvo-goal.valor_atual))}</span></div><div className="mt-5 grid gap-3 rounded-2xl bg-subtle p-4 sm:grid-cols-2"><Projection icon={TrendingUp} label="No ritmo atual" value={projection.date} /><Projection icon={CalendarDays} label="Aporte mensal necessário" value={projection.required} /></div><div className="mt-5 flex flex-wrap gap-2"><MovementDialog goal={goal} accounts={accounts} /><HistoryDialog goal={goal} /></div></CardContent></Card>; }
function GoalDialog({ goal, trigger }: { goal?: Goal; trigger: React.ReactNode }) { const [state, action, pending] = useActionState(saveGoal, {}); const id = useId(); return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{goal ? "Editar meta" : "Nova meta"}</DialogTitle><DialogDescription>Defina valor e prazo para calcularmos o caminho.</DialogDescription></DialogHeader><form action={action} className="space-y-5">{goal ? <input type="hidden" name="id" value={goal.id} /> : null}<div className="grid gap-5 sm:grid-cols-2"><Field name="nome" label="Nome da meta" defaultValue={goal?.nome} placeholder="Ex.: Reserva de emergência" /><Field name="valorAlvo" label="Valor-alvo (R$)" inputMode="decimal" defaultValue={goal ? money(goal.valor_alvo) : ""} placeholder="10.000,00" /><Field name="valorInicial" label="Valor já reservado (R$)" inputMode="decimal" defaultValue={goal ? money(goal.valor_inicial) : "0,00"} /><Field name="dataInicio" label="Data de início" type="date" defaultValue={goal?.data_inicio ?? today()} /><Field name="dataAlvo" label="Data-alvo" type="date" defaultValue={goal?.data_alvo} /></div><div><Label htmlFor={`${id}-description`}>Descrição (opcional)</Label><Textarea className="mt-2" id={`${id}-description`} name="descricao" defaultValue={goal?.descricao ?? ""} maxLength={500} /></div><ColorPicker value={goal?.cor ?? colors[0]} /><Feedback state={state} /><div className="flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Voltar</Button></DialogClose><Button disabled={pending}>{pending ? "Salvando…" : "Salvar meta"}</Button></div></form></DialogContent></Dialog>; }
function MovementDialog({ goal, accounts }: { goal: Goal; accounts: Account[] }) { const [state, action, pending] = useActionState(addGoalMovement, {}); const [type,setType] = useState("aporte"); const id=useId(); return <Dialog><DialogTrigger asChild><Button size="sm"><Plus /> Movimentar</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Movimentar {goal.nome}</DialogTitle><DialogDescription>Aportes e resgates vinculados atualizam o saldo da conta escolhida.</DialogDescription></DialogHeader><form action={action} className="space-y-5"><input type="hidden" name="goalId" value={goal.id} /><SelectField id={`${id}-type`} name="tipo" label="Movimentação" value={type} onChange={setType} options={[{value:"aporte",label:"Aporte"},{value:"resgate",label:"Resgate"},{value:"ajuste",label:"Ajuste manual"}]} /><SelectField id={`${id}-account`} name="accountId" label="Conta vinculada" defaultValue="none" disabled={type === "ajuste"} options={[{value:"none",label:type === "ajuste" ? "Ajuste sem conta" : "Sem movimentar conta"},...accounts.map(a=>({value:a.id,label:`${a.nome} · ${a.instituicao}`}))]} /><div className="grid gap-5 sm:grid-cols-2"><Field name="valor" label="Valor (R$)" inputMode="decimal" placeholder="0,00" /><Field name="data" label="Data" type="date" defaultValue={today()} /></div><div><Label htmlFor={`${id}-note`}>Observação (opcional)</Label><Textarea className="mt-2" id={`${id}-note`} name="observacao" maxLength={500} /></div><Feedback state={state} /><div className="flex justify-end gap-3"><DialogClose asChild><Button type="button" variant="outline">Voltar</Button></DialogClose><Button disabled={pending}>{pending ? "Registrando…" : "Confirmar"}</Button></div></form></DialogContent></Dialog>; }
function HistoryDialog({ goal }: { goal: Goal }) { return <Dialog><DialogTrigger asChild><Button size="sm" variant="outline">Histórico</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Histórico da meta</DialogTitle><DialogDescription>{goal.nome} · movimentações mais recentes</DialogDescription></DialogHeader><div className="space-y-2">{goal.contributions.length ? goal.contributions.map(c=><div key={c.id} className="flex items-center gap-3 rounded-xl bg-subtle p-3"><div className="min-w-0 flex-1"><p className="text-sm font-bold capitalize">{c.tipo}</p><p className="text-xs text-muted-foreground">{dateBR(c.data)}{c.accountName ? ` · ${c.accountName}` : ""}</p></div><p className={c.tipo === "resgate" ? "font-bold text-negative" : "font-bold text-positive"}>{c.tipo === "resgate" ? "−" : "+"}{formatCurrency(c.valor)}</p><DeleteMovement id={c.id} /></div>) : <p className="py-8 text-center text-sm text-muted-foreground">Nenhuma movimentação registrada.</p>}</div></DialogContent></Dialog>; }
function StatusButtons({ goal }: { goal: Goal }) { const [,toggleAction,toggling]=useActionState(changeGoalStatus,{}); const [,cancelAction,cancelling]=useActionState(changeGoalStatus,{}); const next=goal.status === "pausada" ? "ativa" : "pausada"; return <><form action={toggleAction}><input type="hidden" name="id" value={goal.id}/><input type="hidden" name="status" value={next}/><Button variant="ghost" size="icon" disabled={toggling} aria-label={next === "ativa" ? "Retomar meta" : "Pausar meta"}>{next === "ativa" ? <RotateCcw/> : <Pause/>}</Button></form><form action={cancelAction}><input type="hidden" name="id" value={goal.id}/><input type="hidden" name="status" value="cancelada"/><Button variant="ghost" size="icon" disabled={cancelling} aria-label={`Cancelar ${goal.nome}`}><Trash2/></Button></form></>; }
function DeleteMovement({ id }: { id:string }) { const [,action,pending]=useActionState(deleteGoalMovement,{}); return <form action={action}><input type="hidden" name="id" value={id}/><Button variant="ghost" size="icon" disabled={pending} aria-label="Excluir movimentação"><Trash2/></Button></form>; }
function Metric({icon:Icon,label,value}:{icon:typeof Target;label:string;value:string}){return <Card className="rounded-2xl"><CardContent className="flex items-center gap-4 p-5"><span className="rounded-xl bg-brand-soft p-3 text-primary"><Icon className="size-5"/></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-display text-xl font-bold">{value}</p></div></CardContent></Card>}
function Projection({icon:Icon,label,value}:{icon:typeof Target;label:string;value:string}){return <div className="flex gap-2"><Icon className="mt-0.5 size-4 shrink-0 text-primary"/><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div></div>}
function Field({name,label,...props}:React.ComponentProps<typeof Input>&{name:string;label:string}){const id=useId();return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} required {...props}/></div>}
function SelectField({id,name,label,defaultValue,value,onChange,options,disabled}:{id:string;name:string;label:string;defaultValue?:string;value?:string;onChange?:(v:string)=>void;options:{value:string;label:string}[];disabled?:boolean}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Select key={`${disabled}-${options[0]?.label}`} name={name} defaultValue={defaultValue} value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger id={id}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>{disabled ? <input type="hidden" name={name} value="none"/> : null}</div>}
function ColorPicker({value}:{value:string}){return <div><Label>Cor da meta</Label><div className="mt-2 flex gap-3">{colors.map(c=><label key={c} className="cursor-pointer"><input className="peer sr-only" type="radio" name="cor" value={c} defaultChecked={c.toLowerCase()===value.toLowerCase()}/><span className="block size-8 rounded-full border-4 border-background ring-2 ring-transparent peer-checked:ring-foreground" style={{backgroundColor:c}}/></label>)}</div></div>}
function Feedback({state}:{state:GoalState}){return state.message?<Alert className={state.status==="error"?"border-negative/40":"border-positive/40"}><AlertDescription>{state.message}</AlertDescription></Alert>:null}
function calculateProjection(goal:Goal){const remaining=Math.max(0,goal.valor_alvo-goal.valor_atual);const cutoff=new Date();cutoff.setDate(cutoff.getDate()-180);const net=goal.contributions.filter(c=>new Date(`${c.data}T00:00:00`)>=cutoff&&c.tipo!=="ajuste").reduce((s,c)=>s+(c.tipo==="aporte"?c.valor:-c.valor),0);const monthly=Math.max(0,net/6);const monthsLeft=Math.max(1,Math.ceil((new Date(`${goal.data_alvo}T00:00:00Z`).getTime()-Date.now())/2629800000));if(remaining===0)return{date:"Objetivo alcançado",required:"R$ 0,00"};const projected=monthly>0?new Date(Date.now()+Math.ceil(remaining/monthly)*2629800000):null;return{date:projected?dateBR(projected.toISOString().slice(0,10)):"Aguardando aportes",required:formatCurrency(remaining/monthsLeft)}}
function status(v:Goal["status"]){return v==="concluida"?"concluída":v==="pausada"?"pausada":"ativa"}function dateBR(v:string){return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}T00:00:00Z`))}function money(v:number){return new Intl.NumberFormat("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)}function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
